jobs:
  - name: Deploy-to-Development
    serial: true
    plan:
      - get: git-src
        resource: git-src-develop
        trigger: true
      - task: buildapp
        file: git-src/conf/ci/buildapp.yml
        params:
          NEXUS_URL: ((nexus_url))
          NEXUS_USER: ((nexus_user))
          NEXUS_PASSWORD: ((nexus_password))
      - put: cf-development
        params:
          current_app_name: mn-test
          manifest: git-src/conf/ci/manifest.yml
          path: play-app/rws-web-dd-oper-1.0-SNAPSHOT.zip

resources:
  - name: git-src-develop
    type: git
    source:
      uri: ((git_uri))
      username: ((git_username))
      password: ((git_password))
      branch: master

  - name: cf-development
    type: cf
    source:
      api: https://api.system.cf-acc-am2.intranet.rws.nl
      username: ((wm-concourse-integration.username))
      password: ((wm-concourse-integration.password))
      organization: WM
      space: DEV_WM_WEB
